services:
  tailscale-mealie:
    image: tailscale/tailscale:latest
    container_name: tailscale-mealie
    hostname: mealie
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun
    environment:
      - TS_AUTH_KEY=YOUR_TAILSCALE_AUTH_KEY
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_HOSTNAME=mealie
      - TS_ACCEPT_DNS=false
    volumes:
      - ./tailscale:/var/lib/tailscale
    networks:
      - mealie-network

  mealie:
    image: ghcr.io/mealie-recipes/mealie:latest
    container_name: mealie
    restart: unless-stopped
    network_mode: "service:tailscale-mealie"
    depends_on:
      - tailscale-mealie
    volumes:
      - ./data:/app/data
    environment:
      - TZ=Europe/Lisbon
      - DB_ENGINE=sqlite
      - MEALIE_SITE_URL=https://mealie.taila951c1.ts.net
      - MEALIE_ALLOW_SIGNUP=true

networks:
  mealie-network:
    driver: bridge
